# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
name: Java CI with Maven
on:
  push:
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install -DskipTests
  test:
    needs: build
    strategy:
      matrix:
        project: [junit-ext, blazegraph-colt, ctc-striterators, lgpl-utils, dsi-utils, system-utils, rdf-properties, sparql-grammar, bigdata-util, bigdata-common-util, bigdata-statics, bigdata-cache, bigdata-client, bigdata-ganglia, bigdata-gas, bigdata-core, vocabularies, bigdata-war-html, bigdata-blueprints, bigdata-runtime, bigdata-core-test, bigdata-rdf-test, blazegraph-artifacts]
        include:
          - project: bigdata-sails-test
            test: -Dtest=com.bigdata.rdf.sail.sparql.TestAll
          - project: bigdata-sails-test
            test: -Dtest=TestBootstrapBigdataSail
          - project: bigdata-sails-test
            test: -Dtest=TestBigdataSailWithSids
          - project: bigdata-sails-test
            test: -Dtest=TestBigdataSailWithoutSids
          - project: bigdata-sails-test
            test: -Dtest=TestBigdataSailWithQuads
          - project: bigdata-sails-test
            test: -Dtest=com.bigdata.rdf.sail.tck.TestAll
          - project: bigdata-sails-test
            test: -Dtest=com.bigdata.rdf.sail.webapp.TestAll
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B ${{matrix.test}} surefire:test -Dsurefire.rerunFailingTestsCount=2 -f ${{matrix.project}}/pom.xml
  
